inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
Metrics/LineLength:
  Max: 120
  Exclude:
    - config/routes.rb
Metrics/BlockLength:
  Exclude:
    - Guardfile
    - config/Guardfile
    - spec/**/*
Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*
Style/Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/FormatStringToken:
  Enabled: false
Rails/OutputSafety:
  Exclude:
    - lib/bootstrap_link_renderer.rb