inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - 'bin/**/*'
    - db/schema.rb
Metrics/LineLength:
  Max: 120
  Exclude:
    - config/routes.rb
Style/Documentation:
  Enabled: false
Rails:
  Enabled: true