language: ruby
cache:
  - bundler
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_install:
  - gem install bundler
bundler_args: --without production
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle exec rails yarn:install
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rails webpacker:compile RAILS_ENV=test
script:
  - bundle exec yarn lint
  - bundle exec rails factory_bot:lint
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
